steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
  
  # Build the application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
  
  # Deploy to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gsutil
    args: ['-m', 'cp', '-r', 'dist/*', 'gs://snapeat-website/']
